version: 0.0
os: linux
files:
  - source: application.war
    destination: /opt/apache-tomcat-7.0.67/webapps
permissions:  
  - object: /opt/apache-tomcat-7.0.67/webapps
    pattern: "application.war"
    owner: ec2-user
    group: ec2-user
    mode: 600
    type:
      - file
hooks:  
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      timeout: 350